# Site settings
title: Bogdan Poplauschi's blog
description: >- # newlines until "baseurl:"
  Welcome to my personal blog. It contains posts based on my experience in the field of Software Developement and more.
baseurl: ""
url: "https://bpoplauschi.github.io"

# User settings
email: bpoplauschi@gmail.com
twitter_username: null
github_username:  bpoplauschi

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

google_analytics: G-BQ7W0SRF54
issues_repo: bpoplauschi/bpoplauschi.github.io
exclude:
   - Gemfile
   - Gemfile.lock
   - README.md
